{% set version = "0.6.1" %}

package:
  name: webencodings
  version: {{ version }}

source:
  fn: webencodings-{{ version }}.tar.gz
  url: https://github.com/CourtBouillon/webencodings/archive/v{{ version }}.tar.gz
  sha256: 10fbb39ffbebf229552c7ede0172313c0612e2ff88259223b94db77a66f8b889

build:
  number: 0
  skip: True  # [py<310]
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - flit-core >=3.2,<5
    - pip
  run:
    - python

test:
  imports:
    - webencodings
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/CourtBouillon/webencodings
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://doc.courtbouillon.org/webencodings
  dev_url: https://github.com/CourtBouillon/webencodings
  summary: Character encoding aliases for legacy web content

extra:
  recipe-maintainers:
    - jschueller
