travis:
  secure:
    BINSTAR_TOKEN: lpznDkeELPtOQWaXIepojdXVrC5j3SJyeKwiYpDL6ibcUX5JaYY8DtHRU5AxhfTCTc/Kwy6/zDfWdeHjgz5hbwR1kIIk5zBGFd/rUYf7RNJ4t7m3oway+vVz/nTpEyx5xqOMx3guwooAPBSxsx3kaQqdGec0bfGxUZqxnGb2foIaA43+w4Pfv4RaZpwIlo+RpA5+EABAbtg3lFs2D1jHAAnUXfBGHmpNvniRZOo+l6hjf1qOdBFwY08+63hoyZ5LqaK0ErzxB1zlZTCn1AV7n/KRGI2B9ixBooaqsqfgu9t5EuUam0Ud6xeol5j0OSxV6ldBf9dQpiJDA6N4xCQZN6mvT/sL6tIn+O/F+6c5/3GGFRaKMluyIkjgRTlzNPY8PXSD0sJLs5koRzmyvludewvVRxg5DsjabldIpOdoNrnttKutLW2CNa2wqIx62zSH68/RM5rV9SKBsuOVaObwr6WA3qtb3W06TuZWe/gDgcHaKCQeqR27wC3FvaIrXeuFE/3X47CL7R82//ISRIMTMklgWyUsfY10KVUEQrdpmpkX2O2P4itaZbLbNQ1xgxwWIyW8cfyuBHAxv27P0iK7hfNbQiDotMi3WRd8INSSvaupqnM9KJOFDifrP/d5a3+S4mhH3z+h+1lr9wxqaEngvNXYBgwVETC4IB6M00IouK0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
